### ISSUE TITLE
Not possible to create/update a sidebar

### ISSUE THREAD

**Issue by akaha** [intoxstudio/content-aware-sidebars#5]
Hello. I've got WP version 4.5.1 and CAS version 3.1.2. Some updates before everything worked but now I can't create/update sidebars. When I select the content type a javascript error occurs in the console (no useful message because of minification) and no further selectbox is shown for the advanced options. When I save the changes are not visible/saved and I can't use this sidebar for widgets.

Do you have a hint for me what can be wrong or how to debug? It seems to me that I am the only one with this problem because here is no other issue yet. I deinstalled and installed several times.

**Comment by intoxstudio** [comment]
Thank you for reporting this.

I have seen similar problems here: https://wordpress.org/support/plugin/content-aware-sidebars

In all cases it has been because of incompatibilities with other plugins or the theme. Can you see if this is the case here?

**Comment by akaha** [comment]
Yes, you're right. In my case it was the Tabs Responsive plugin. Thank you.
