### ISSUE TITLE
After updating to 3.5 all the widgets –within (Content Aware) sidebars– are gone.

### ISSUE THREAD

**Issue by diegocanal** [intoxstudio/content-aware-sidebars#7]
Hi! Please let me know what information I should include to properly report the issue.

**Comment by intoxstudio** [comment]
Could you please provide the WordPress version and PHP version?
And is it only the widgets that dissappeared, the sidebars still exist as they were?

Perhaps the widgets have been moved to "Inactive Widgets" for some reason, try navigating to Appearance > Widgets:

[![https://gyazo.com/1c98994601f282019f4751da43647615](https://i.gyazo.com/1c98994601f282019f4751da43647615.gif)](https://gyazo.com/1c98994601f282019f4751da43647615)

**Comment by diegocanal** [comment]
Thanks for your prompt response.

WP version: 4.7.3
PHP version: 7.0.15

**Within the backend everything looks OK** (widgets, sidebars, plugin settings)...**the problem is only within the frontend**, the widgets that should be placed ("replaced") by Content-Aware-Sidebars are gone.

As I said, the widgets have not been moved to "Inactive Widgets" they are where they are supposed to be.

I would be willing to send you credentials to get access to the backend in case you wanted to take a look by yourself...or if you prefer some screenshots just let me know.

**Comment by intoxstudio** [comment]
Could you send the credentials via https://dev.institute/contact/? Then I will take a look. I cannot reproduce the problem you are describing.

**Comment by diegocanal** [comment]
Credentials sent. Thanks!
