### ISSUE TITLE
after upgraded this error come out

### ISSUE THREAD

**Issue by agoraclx** [intoxstudio/content-aware-sidebars#8]
Fatal error: Uncaught Error: Call to undefined function cas_fs() in /Applications/AMPPS/www/mogproperty.mog/wp-content/plugins/content-aware-sidebars/admin/sidebar-list-table.php:596 Stack trace: #0 /Applications/AMPPS/www/mogproperty.mog/wp-content/plugins/content-aware-sidebars/admin/sidebar-list-table.php(428): CAS_Sidebar_List_Table->handle_row_actions(Object(WP_Post), 'title', 'title') #1 /Applications/AMPPS/www/mogproperty.mog/wp-content/plugins/content-aware-sidebars/admin/sidebar-list-table.php(382): CAS_Sidebar_List_Table->column_title(Object(WP_Post)) #2 /Applications/AMPPS/www/mogproperty.mog/wp-admin/includes/class-wp-list-table.php(1245): CAS_Sidebar_List_Table->_column_title(Object(WP_Post), 'title column-ti...', 'data-colname="T...', 'title') #3 /Applications/AMPPS/www/mogproperty.mog/wp-content/plugins/content-aware-sidebars/admin/sidebar-list-table.php(575): WP_List_Table->single_row_columns(Object(WP_Post)) #4 /Applications/AMPPS/www/mogproperty.mog/wp-admin/includes/class-wp-list-table.php(1180): CAS_Si in /Applications/AMPPS/www/mogproperty.mog/wp-content/plugins/content-aware-sidebars/admin/sidebar-list-table.php on line 596

content-aware-sidebars Version: 3.7.6
Php Version: 7.0.
WordPress Version 4.9.6

**Comment by intoxstudio** [comment]
Thanks for reporting this!

Did you update the plugin from the Plugins screen? Or do you update e.g. via a staging environment?
Does the file `wp-content/plugins/content-aware-sidebars/freemius.php` exist on your server?

I just released version 3.7.7, so please see if updating to that resolves the problem.
